### ISSUE TITLE
AttributeError: module 'ScoreDraft' has no attribute 'jklex_UTAU'

### ISSUE THREAD

**Issue by melspectrum007** [fynv/ScoreDraft#6]
When I run the script KeLaTest.py, error is happen as list bellow. It seems ScoreDraft has  no attribute 'jklex_UTAU'.

Traceback (most recent call last):
  File "KeLaTest.py", line 13, in <module>
    doc.sing(seq, ScoreDraft.jklex_UTAU())
AttributeError: module 'ScoreDraft' has no attribute 'jklex_UTAU'

**Comment by fynv** [comment]
What you need to do here is:
1. Download the jklex voicebank from http://pan.baidu.com/s/1mi6N6oK
2. Unzip and put the folder at python_test\UTAUVoice\jklex
Then there will be ScoreDraft.jklex_UTAU() next time you run the script.
For copyright issues and compactness, the GitHub repository contains very few wav samples.

**Comment by melspectrum007** [comment]
Thanks for your prompt reply. 

There some error of the Examples. Such as 
**python uta_test.py**

Traceback (most recent call last):
  File "uta_test.py", line 14, in <module>
    doc.sing(seq, ScoreDraft.uta_UTAU())
AttributeError: module 'ScoreDraft' has no attribute 'uta_UTAU'

**python RapTest.py**
TypeError: must be real number, not TrackBuffer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "RapTest.py", line 66, in <module>
    doc.sing(seq, ScoreDraft.GePing_UTAU())
  File "..\Meteor.py", line 58, in sing
    ScoreDraft.MeteorProcessSingingSeq(self.visualizerId, singer, buf, seq, self
.tempo, self.refFreq)
  File "<string>", line 104, in MeteorProcessSingingSeq
SystemError: <built-in function CallExtension> returned a result with an error s
et

**Comment by fynv** [comment]
* "AttributeError: module 'ScoreDraft' has no attribute 'uta_UTAU'"
The same issue. Here you need the UTAU\voice\uta folder. Copy it to python_test\UTAUVoice\uta
* About RapTest.py
First, you need the full GePing voicebank: http://utau.vocalover.com/newgeping.html
Second, seems some binary modules were broken. I fixed that by the last commit. Please pull or download gain. Sorry for the inconvenience.

**Comment by fynv** [comment]
Your question reminded me that I should put a link to the voicebank in every example.

**Comment by melspectrum007** [comment]
When I pu the link in the given folder, it works well.
But for WuYa.py, it misses RockMute(), AlansGuitar(), Bass().

GuitarMute=ScoreDraft.RockMute()
Guitar=ScoreDraft.AlansGuitar()
Bass=ScoreDraft.Bass()

The errors are shown bellow:
  _File "WuYa.py", line 59, in <module>
    GuitarMute=ScoreDraft.RockMute()
AttributeError: module 'ScoreDraft' has no attribute 'RockMute'

Traceback (most recent call last):
  File "WuYa.py", line 60, in <module>
    Guitar=ScoreDraft.AlansGuitar()
AttributeError: module 'ScoreDraft' has no attribute 'AlansGuitar'

  File "WuYa.py", line 61, in <module>
    Bass=ScoreDraft.Bass()
AttributeError: module 'ScoreDraft' has no attribute 'Bass'_

**Comment by melspectrum007** [comment]
By the way, my OS is win64, and I didn't compile the source code, I just use the pre-deployed binaries.
Do I need to compile the source code myself to make it work normal?

**Comment by fynv** [comment]
You need to download some instrumental samples (.wav file) and put them into 
python_test\InstrumentSamples
I grabbed all these samples from https://freewavesamples.com/

**Comment by fynv** [comment]
Can't remember which one is the AlansGuitar I'm using here. I renamed the file..
It is quite safe to use another Guitar tone as a substitution, just that you will get different sound.

**Comment by melspectrum007** [comment]
I'm very sorry that there is another problem I run into.

**python NaushikaRequiem.py**

  File "NaushikaRequiem.py", line 17, in <module>
    doc.setReferenceFreqeuncy(264.0)
AttributeError: 'Document' object has no attribute 'setReferenceFreqeuncy'

**Comment by fynv** [comment]
That's a very old typo that affected many files.
setReferenceFreqeuncy=> setReferenceFrequency
I hope this is the only one I forgot to fix..
And, please don't say sorry. I'm the one to say sorry.
Thanks for testing.
